version: '3.9'

services:
  postgres-db:
    image: postgres:15
    container_name: ttrpgmanager-postgres
    environment:
      POSTGRES_DB: ttrpg_db
      POSTGRES_USER: GMMoons
      POSTGRES_PASSWORD: MadMoons!
    ports:
      - "5432:5432"
    networks:
      - ttrpg-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo-db:
    image: mongo:6
    container_name: ttrpgmanager-mongo
    ports:
      - "27017:27017"
    networks:
      - ttrpg-network
    volumes:
      - mongo_data:/data/db

  ttrpgmanager-backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ttrpgmanager-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - mongo-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/ttrpg_db
      SPRING_DATASOURCE_USERNAME: GMMoons
      SPRING_DATASOURCE_PASSWORD: MadMoons!
      SPRING_MONGODB_URI: mongodb://mongo-db:27017/ttrpg_db
    networks:
      - ttrpg-network

networks:
  ttrpg-network:
    external: true

volumes:
  postgres_data:
  mongo_data:


